// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "capi_kpack_watcher/model"

	mock "github.com/stretchr/testify/mock"
)

// APIRequester is an autogenerated mock type for the APIRequester type
type APIRequester struct {
	mock.Mock
}

// UpdateBuild provides a mock function with given fields: token, guid, status
func (_m *APIRequester) UpdateBuild(token string, guid string, status model.BuildStatus) error {
	ret := _m.Called(token, guid, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, model.BuildStatus) error); ok {
		r0 = rf(token, guid, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
