// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// REST is an autogenerated mock type for the REST type
type REST struct {
	mock.Mock
}

// PATCH provides a mock function with given fields: url, authToken, body
func (_m *REST) PATCH(url string, authToken string, body io.Reader) error {
	ret := _m.Called(url, authToken, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, io.Reader) error); ok {
		r0 = rf(url, authToken, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
